version: '3.8'

networks:
  postgres-network:
    name: postgres-network

volumes:
  postgres-data:
    name: postgres-data
  pgadmin-data:
    name: pgadmin-data
  
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped 

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres-network
    depends_on:
      - postgres # Very important to let postgres start first
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped 